name: "Build firmwares"

# Run this job on all pushes to master, for pull requests
# as well as tags with a semantic version
on:
  push:
    branches:
      # This avoids having duplicate builds in non-forked PRs
      - "master"
  release:
    types:
      - published
  pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: 'build-firmware-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.device }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - zwa2
          - zbt2

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Create output directory
      run: mkdir -p output

    - name: ESP-IDF build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32s3
        extra_docker_args: -e SDKCONFIG_DEFAULTS=sdkconfig.defaults-${{ matrix.device }}

    - name: Create factory bin
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32s3
        path: build
        command: |
          esptool.py \
            merge_bin \
            -o ../output/${{ matrix.device }}-esp-bridge.factory.bin \
            @flash_args

    - name: Copy app bin
      working-directory: build
      run: cp usb2uart.bin ../output/${{ matrix.device }}-esp-bridge.bin

    - name: MD5
      working-directory: output
      run: |
        md5sum ${{ matrix.device }}-esp-bridge.bin > ${{ matrix.device }}-esp-bridge.bin.md5
        md5sum ${{ matrix.device }}-esp-bridge.factory.bin > ${{ matrix.device }}-esp-bridge.factory.bin.md5

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.device }}
        path: output/

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          output/${{ matrix.device }}-esp-bridge.bin
          output/${{ matrix.device }}-esp-bridge.bin.md5
          output/${{ matrix.device }}-esp-bridge.factory.bin
          output/${{ matrix.device }}-esp-bridge.factory.bin.md5
